package javaapplication1;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.*;

/**
 *
 * @author rolando
 */
public class sdasd extends javax.swing.JFrame {

    ImageIcon icon = new ImageIcon("aaa.png");
    JLabel label = new JLabel();
    ArrayList<Seccion> arr = new ArrayList<Seccion>();
    ArrayList<Float> arre = new ArrayList<Float>();
    ArrayList<ImageIcon> imgs = new ArrayList<ImageIcon>();

    /**
     * Creates new form sdasd
     */
    public sdasd() {
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        initComponents();
        //setLayout(new GridLayout(1, 2));
        setSize(941, 707);
        setVisible(true);
        

        arr.add(new Seccion((float) 1500.0, 814000, "N-80", (float) 35.00, 80000, (float) 10.172));
        arr.get(arr.size() - 1).setFondo(12000);
        arr.add(new Seccion((float) 1500.0, 745000, "N-80", (float) 32.00, 80000, (float) 9.317));
        arr.get(arr.size() - 1).setFondo(10500);
        arr.add(new Seccion((float) 2400.0, 676000, "N-80", (float) 29.00, 80000, (float) 8.449));
        arr.get(arr.size() - 1).setFondo(9000);
        arr.add(new Seccion((float) 6600.0, 366000, "J-55", (float) 20.00, 80000, (float) 6.656));
        arr.get(arr.size() - 1).setFondo(6600);
        arr.add(new Seccion((float) 6600.0, 366000, "J-55", (float) 20.00, 80000, (float) 6.656));
        arr.add(new Seccion((float) 6600.0, 366000, "J-55", (float) 19.00, 80000, (float) 6.656));
        arr.add(new Seccion((float) 6600.0, 366000, "J-55", (float) 18.00, 80000, (float) 6.656));
        arr.add(new Seccion((float) 6600.0, 366000, "J-55", (float) 17.00, 80000, (float) 6.656));
        arr.add(new Seccion((float) 6600.0, 366000, "J-55", (float) 16.00, 80000, (float) 6.656));
        arr.add(new Seccion((float) 6600.0, 366000, "J-55", (float) 15.00, 80000, (float) 6.656));
        
        ImageIcon img = new ImageIcon(getClass().getResource("/javaapplication1/10.png"));
        img = new ImageIcon(img.getImage().getScaledInstance(240, 180, java.awt.Image.SCALE_SMOOTH));
        imgs.add(img);
        img = new ImageIcon(getClass().getResource("/javaapplication1/9.png"));
        img = new ImageIcon(img.getImage().getScaledInstance(240, 180, java.awt.Image.SCALE_SMOOTH));
        imgs.add(img);
        img = new ImageIcon(getClass().getResource("/javaapplication1/8.png"));
        img = new ImageIcon(img.getImage().getScaledInstance(240, 180, java.awt.Image.SCALE_SMOOTH));
        imgs.add(img);

        img = new ImageIcon(getClass().getResource("/javaapplication1/7.png"));
        img = new ImageIcon(img.getImage().getScaledInstance(240, 180, java.awt.Image.SCALE_SMOOTH));
        imgs.add(img);

        img = new ImageIcon(getClass().getResource("/javaapplication1/6.png"));
        img = new ImageIcon(img.getImage().getScaledInstance(240, 180, java.awt.Image.SCALE_SMOOTH));
        imgs.add(img);

        img = new ImageIcon(getClass().getResource("/javaapplication1/5.png"));
        img = new ImageIcon(img.getImage().getScaledInstance(240, 180, java.awt.Image.SCALE_SMOOTH));
        imgs.add(img);

        img = new ImageIcon(getClass().getResource("/javaapplication1/4.png"));
        img = new ImageIcon(img.getImage().getScaledInstance(240, 180, java.awt.Image.SCALE_SMOOTH));
        imgs.add(img);

        img = new ImageIcon(getClass().getResource("/javaapplication1/3.png"));
        img = new ImageIcon(img.getImage().getScaledInstance(240, 180, java.awt.Image.SCALE_SMOOTH));
        imgs.add(img);

        img = new ImageIcon(getClass().getResource("/javaapplication1/2.png"));
        img = new ImageIcon(img.getImage().getScaledInstance(240, 180, java.awt.Image.SCALE_SMOOTH));
        imgs.add(img);

        img = new ImageIcon(getClass().getResource("/javaapplication1/1.png"));
        img = new ImageIcon(img.getImage().getScaledInstance(240, 180, java.awt.Image.SCALE_SMOOTH));
        imgs.add(img);
        mostrartubos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();

        setResizable(false);

        scrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("lului"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(475, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mostrartubos() {


        int y = 10;
        //JScrollPane scrollPane = new JScrollPane();
//        scrollPane.setBorder(BorderFactory.createLoweredSoftBevelBorder());

        JPanel panelImg = new JPanel();
        panelImg.setLayout(null);
        panelImg.setPreferredSize(new Dimension(210, arr.size() * 182));
        //panelImg.setBounds(y, 2, 450, (arr.size() * 181));
        //scrollPane.setPreferredSize(new Dimension(600,arr.size() * 401));
        panelImg.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        Collections.sort(arr, new Comparator<Seccion>() {

            @Override
            public int compare(Seccion p1, Seccion p2) {
                return (int) (p2.getPeso() - p1.getPeso());
            }
        });

        for (int i = 0; i < arr.size(); i++) {

            System.err.println(arr.get(i).getPeso());
            arre.add(arr.get(i).getPeso());

        }


        for (int i = 0; i < arr.size(); i++) {


            JLabel intervalo = new JLabel();
            JLabel longitud = new JLabel();
            JLabel grado = new JLabel();
            JLabel etiqueta = new JLabel();
            JLabel sexion = new JLabel();
            //etiqueta.setText("jodr");
            etiqueta.setBounds(40, y, 240, 180);

            for (int j = 0; j < arre.size(); j++) {
                System.out.println(arr.get(i).getPeso() + " sdsd " + arre.get(j));
                if ((float) arr.get(i).getPeso() == arre.get(j)) {
                    arre.remove(j);
                    if (imgs.size() - 1 > j) {
                        etiqueta.setIcon(imgs.get(j));
                        imgs.remove(j);
                    } else {
                        etiqueta.setIcon(imgs.get(imgs.size() - 1));
                    }
                    System.out.println("sdsd");
                }

            }
            sexion.setText("sfsaf");
            grado.setText("dsds");
            longitud.setText("sadsd");
            intervalo.setText("sadas");
            
            intervalo.setBounds(300, y, 80, 80);
            sexion.setBounds(300, y+40, 80, 80);
            grado.setBounds(300, y + 60, 80, 80);
            longitud.setBounds(300, y + 20, 80, 80);

            //scrollPane.setBounds(10, 101, 742, 276);
            //scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
            panelImg.add(intervalo);
            panelImg.add(sexion);
            panelImg.add(grado);
            panelImg.add(longitud);
            panelImg.add(etiqueta);

            y = y + 180;
        }

        panelImg.repaint();
        panelImg.revalidate();
        //scrollPane.setBounds(50, 10, 300, 700);
        //scrollPane.setPreferredSize(new Dimension(200, 500));
        //scrollPane.setVerticalScrollBarPolicy(scrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setViewportView(panelImg);
        getContentPane().add(scrollPane);

    }

    public static void main(String args[]) {

        new sdasd().mostrartubos();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
